CREATE FUNCTION CAMP_CLIENTE_EFETIVADO(@CODPARC INT)
RETURNS INT
AS
/*
-- Autor:		<LUIS RAPKIEVICZ>
-- Data: 		<21/03/2023>
-- Objetivo:	<VERIFICA SE O CLIENTE FOI EFETIVADO NO MES CORRENTE RETORNANDO 1 PARA SIM E 0 PARA NAO>
*/
BEGIN
    DECLARE @RESULT     INT;
    
	SELECT
        @RESULT = (
            CASE WHEN DATEPART(MONTH,MAX(CAB.DTNEG)) = DATEPART(MONTH,GETDATE()) 
                        AND DATEPART(YEAR,MAX(CAB.DTNEG)) = DATEPART(YEAR,GETDATE())
                    THEN 1
                ELSE 0
                END
        )
    FROM
        TGFCAB CAB
    WHERE
        CAB.CODPARC = @CODPARC
            AND CAB.CODTIPOPER IN (SELECT DISTINCT CODTIPOPER FROM TGFTOP WHERE GOLSINAL = -1)
            AND CAB.STATUSNOTA = 'L'

	RETURN @RESULT
END